### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by BobGu** [krogowsk531/mod_0_skills#1]
Hi @krogowsk531. Thanks for your hard work on this. I like your use of multiple data types in the `Menu` class.  Also I like the use of two attributes to do a calculation, for example `getTipsMadePerHour` is a really nice method.

- [x] It looks like for the `Maggiano's` example there is an attribute that doesn't exist on the `Menu` class. Can you fix this?

**Comment by krogowsk531** [comment]
It's fixed.  Thank you for the feedback!
